package edu.ecnu.sei.st2019;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ChangeTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void change() {
    driver.get("http://localhost:8080/login");
    driver.manage().window().setSize(new Dimension(1200, 824));
    driver.findElement(By.cssSelector(".el-row:nth-child(1) input")).click();
    driver.findElement(By.cssSelector(".el-row:nth-child(1) input")).sendKeys("zh");
    driver.findElement(By.cssSelector(".el-row:nth-child(2) input")).click();
    driver.findElement(By.cssSelector(".el-row:nth-child(2) input")).sendKeys("123456");
    driver.findElement(By.cssSelector(".logIN")).click();
    driver.findElement(By.cssSelector(".el-menu-item:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".el-menu-demo > .el-menu-item:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".el-table__row:nth-child(3) .el-icon")).click();
    driver.findElement(By.cssSelector(".el-col:nth-child(1) .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-date-picker__editor-wrap:nth-child(2) .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-time-spinner__wrapper:nth-child(1) .el-time-spinner__item:nth-child(10)")).click();
    driver.findElement(By.cssSelector(".confirm")).click();
    driver.findElement(By.cssSelector(".el-picker-panel__footer")).click();
    driver.findElement(By.cssSelector(".el-button--default > span")).click();
    driver.close();
  }
}
