// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SiyeTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void siye() {
    driver.get("http://localhost:8080/index/siteDetail/2");
    driver.manage().window().setSize(new Dimension(1200, 800));
    driver.findElement(By.cssSelector(".el-date-editor--date > .el-input__inner")).click();
    driver.findElement(By.cssSelector(".available span")).click();
    driver.findElement(By.cssSelector(".el-date-editor:nth-child(2) > .el-input__inner")).click();
    driver.findElement(By.cssSelector(".time-select-item:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".el-date-editor:nth-child(3) > .el-input__inner")).click();
    driver.findElement(By.cssSelector(".el-picker-panel:nth-child(8) .time-select-item:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".el-button:nth-child(5) > span")).click();
    driver.findElement(By.cssSelector(".but:nth-child(1) > span")).click();
    driver.findElement(By.cssSelector(".but:nth-child(1) > span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".but:nth-child(1) > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".el-textarea__inner")).click();
    driver.findElement(By.cssSelector(".el-textarea__inner")).sendKeys("rangworjts");
    driver.findElement(By.cssSelector(".el-button:nth-child(3) > span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".el-button:nth-child(3) > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".el-button--primary")).click();
    driver.findElement(By.cssSelector(".el-row:nth-child(1) input")).click();
    driver.findElement(By.cssSelector(".el-row:nth-child(1) input")).sendKeys("zh");
    driver.findElement(By.cssSelector(".el-row:nth-child(2) input")).click();
    driver.close();
  }
}
