package edu.ecnu.sei.st2019;// Generated by Selenium IDE


import edu.ecnu.sei.st2019.Pages.BasePage;
import edu.ecnu.sei.st2019.Pages.HomePage;
import edu.ecnu.sei.st2019.Pages.SearchPage;
import edu.ecnu.sei.st2019.Pages.SearchResultPage;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static edu.ecnu.sei.st2019.DriverSingleton.waitForWindow;
import static org.hamcrest.MatcherAssert.assertThat;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.*;

public class StudentNoticeSearchTest extends BaseTest {

   BasePage basePage = new BasePage();
   HomePage homePage = new HomePage();
   SearchPage searchPage = new SearchPage();
   SearchResultPage resultPage = new SearchResultPage();

  @Test
  public void should_search_notice_for_student() {

//    homePage.goHomePage();
//    homePage.clickLink("在校学生");
//    homePage.putHandler("window_handles");
//    homePage.clickLink("通知公告");
//    homePage.putWin("win4185");
//    homePage.putHandler("root");
//    homePage.switchToWin("win4185");

    homePage.goHomePage()
            .clickLink("在校学生")
            .putHandler("window_handles")
            .clickLink("通知公告")
            .putWin("win4185")
            .putHandler("root")
            .switchToWin("win4185");


//    searchPage.searchNotice("四六级");
//    searchPage.putHandler("window_handles");
//    searchPage.clickSearch();
//    searchPage.putWin("win9039");
//    searchPage.switchToWin("win9039");
//    searchPage.verifyTitle("四六级 - WebplusPro 搜索");
//    searchPage.putHandler("window_handles");

    searchPage.searchNotice("四六级")
              .putHandler("window_handles")
              .clickSearch()
              .putWin("win9039")
              .switchToWin("win9039")
              .verifyTitle("四六级 - WebplusPro 搜索")
              .putHandler("window_handles");

    resultPage.showNotice("2")
              .putWin("win9254")
              .switchToWin("win9254")
              .verifyTitle("关于2019年下半年全国大学英语四六级考试的通知");


    basePage.closePage("win9254")
            .closePage("win9039")
            .closePage("win4185");
  }
}
